# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

# go version.
go:
  -  1.11.2

os:
  - linux
  - osx


install: true


script: 
  - env GO111MODULE=on go build 
  - go test -v ./tests/